import type { LandingCopy } from "./types";

export const en: LandingCopy = {
  nav: {
    product: "Product",
    manager: "Manager workflow",
    teacher: "Teacher view",
    architecture: "Architecture",
    exploreDemo: "Explore live demo",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    langEn: "EN",
    langVi: "VI",
    langGroup: "Language",
  },
  hero: {
    eyebrow: "Interactive product prototype",
    headline: "Turn fragmented school schedules into one operational truth.",
    body: "ClassFlow normalizes inconsistent school data, detects scheduling risks, keeps teacher pay in sync, and turns every manager update into a clear teacher schedule.",
    primaryCta: "Explore live demo",
    secondaryCta: "View teacher experience",
    honesty: "Built with realistic mock data. Demo changes reset on refresh.",
    vignetteLabel: "Manager timeline · sample week",
    conflictLabel: "Double-booking",
    travelLabel: "Tight travel",
    rateLabel: "Rate",
  },
  problem: {
    headline: "Every school describes the same lesson differently.",
    sourceLabel: "School spreadsheets",
    canonicalLabel: "Canonical Lesson",
    fields: {
      teacher: "teacher",
      group: "group",
      school: "school",
      campus: "campus",
      time: "time",
      duration: "duration",
      status: "status",
      rate: "rate",
    },
  },
  manager: {
    headline: "One workspace for the person responsible for the whole schedule.",
    steps: [
      "Import inconsistent school data.",
      "Review mapping before lessons are created.",
      "Detect double-bookings and tight travel gaps.",
      "Move or cancel a lesson and recalculate pay.",
    ],
  },
  sync: {
    headline: "The manager changes one lesson. Everything downstream stays consistent.",
    changeLabel: "Move Wednesday’s lesson from 09:45 to 10:30.",
    before: "Before",
    after: "After",
    timeline: "Manager timeline",
    status: "Conflict / travel",
    earnings: "Earnings",
    teacherSchedule: "Teacher schedule",
    travelCleared: "Travel gap cleared",
    travelRisk: "28 min travel gap",
    travelOkNote: "Gap ≥ 45 min between campuses.",
    travelRiskNote: "Same teacher, different campus, gap < 45 min.",
    payStable: "Hours unchanged · pay stable",
    payTracks: "Pay tracks delivered hours",
    applyMove: "Apply move",
    undoMove: "Show before",
  },
  teacher: {
    headline: "Teachers see what they need—without managing the system.",
    body: "One read-only schedule across every school, with clear lesson status, location, duration and earnings in USD and VND.",
    phoneLabel: "Teacher view",
    earningsLabel: "Week earnings",
    weekLabel: "This week",
  },
  rules: {
    headline: "Domain rules encoded in the product",
    items: [
      "Lesson is the atomic unit.",
      "Manager writes; teacher reads.",
      "Pay is derived from delivered hours.",
      "Cancelled and no-show lessons are unpaid.",
      "VND is derived from one USD exchange rate.",
      "Lesson height reflects its duration.",
      "Scheduling risks are derived, not manually entered.",
    ],
  },
  architecture: {
    headline: "Built as a product system, not a static portfolio mockup.",
    body: [
      "Next.js App Router, React, and TypeScript with a typed Lesson domain model.",
      "Manager and teacher screens project the same in-memory store through shared hooks.",
      "Conflicts, travel gaps, and pay are derived in pure domain functions—never typed in by hand.",
      "UI talks to a DataSource seam, so a real API could replace fixtures without rewriting screens.",
      "Reusable primitives (Badge, MoneyPair, schedule cards) keep both roles visually consistent.",
    ],
    honesty:
      "The current public version is a high-fidelity front-end prototype. Authentication, persistence and production APIs are outside this demo scope.",
  },
  footer: {
    headline: "See the product thinking in action.",
    credit: "Designed and built by Daniel Aleksandrov",
    role: "Frontend Developer · React · Next.js · TypeScript",
    managerLink: "Manager demo",
    teacherLink: "Teacher experience",
  },
  positioning: "Built around real language-school operations. Designed for complex education scheduling.",
};
