import type { LandingCopy } from "./types";

export const vi: LandingCopy = {
  nav: {
    product: "Sản phẩm",
    manager: "Quy trình quản lý",
    teacher: "Góc giáo viên",
    architecture: "Kiến trúc",
    exploreDemo: "Xem demo trực tiếp",
    openMenu: "Mở menu",
    closeMenu: "Đóng menu",
    langEn: "EN",
    langVi: "VI",
    langGroup: "Ngôn ngữ",
  },
  hero: {
    eyebrow: "Nguyên mẫu sản phẩm tương tác",
    headline: "Biến những lịch học rời rạc thành một nguồn dữ liệu vận hành duy nhất.",
    body: "ClassFlow chuẩn hóa dữ liệu trường học không đồng nhất, phát hiện rủi ro xếp lịch, giữ thù lao giáo viên đồng bộ, và biến mọi cập nhật của quản lý thành lịch rõ ràng cho giáo viên.",
    primaryCta: "Xem demo trực tiếp",
    secondaryCta: "Xem góc giáo viên",
    honesty: "Dùng dữ liệu giả lập thực tế. Thay đổi trong demo sẽ mất khi tải lại trang.",
    vignetteLabel: "Timeline quản lý · tuần mẫu",
    conflictLabel: "Trùng lịch",
    travelLabel: "Di chuyển gấp",
    rateLabel: "Mức lương",
  },
  problem: {
    headline: "Mỗi trường mô tả cùng một buổi học theo cách khác nhau.",
    sourceLabel: "Bảng tính từ trường",
    canonicalLabel: "Lesson chuẩn",
    fields: {
      teacher: "giáo viên",
      group: "lớp",
      school: "trường",
      campus: "cơ sở",
      time: "giờ",
      duration: "thời lượng",
      status: "trạng thái",
      rate: "mức lương",
    },
  },
  manager: {
    headline: "Một không gian làm việc cho người quản lý toàn bộ lịch học.",
    steps: [
      "Nhập dữ liệu trường học không đồng nhất.",
      "Rà soát ánh xạ trước khi tạo buổi học.",
      "Phát hiện trùng lịch và khoảng di chuyển quá sát.",
      "Dời hoặc hủy buổi học và tính lại thù lao.",
    ],
  },
  sync: {
    headline: "Quản lý đổi một buổi học. Mọi thứ liên quan tự động cập nhật.",
    changeLabel: "Dời buổi học Thứ Tư từ 09:45 sang 10:30.",
    before: "Trước",
    after: "Sau",
    timeline: "Timeline quản lý",
    status: "Xung đột / di chuyển",
    earnings: "Thù lao",
    teacherSchedule: "Lịch giáo viên",
    travelCleared: "Đã hết khoảng di chuyển sát",
    travelRisk: "Khoảng di chuyển 28 phút",
    travelOkNote: "Khoảng cách ≥ 45 phút giữa các cơ sở.",
    travelRiskNote: "Cùng giáo viên, khác cơ sở, khoảng cách < 45 phút.",
    payStable: "Số giờ không đổi · thù lao ổn định",
    payTracks: "Thù lao theo số giờ đã dạy",
    applyMove: "Áp dụng dời lịch",
    undoMove: "Xem trạng thái trước",
  },
  teacher: {
    headline: "Giáo viên chỉ thấy những gì họ cần — không phải quản trị cả hệ thống.",
    body: "Một lịch chỉ đọc trên mọi trường, với trạng thái buổi học, địa điểm, thời lượng và thù lao rõ ràng bằng USD và VND.",
    phoneLabel: "Góc giáo viên",
    earningsLabel: "Thù lao tuần",
    weekLabel: "Tuần này",
  },
  rules: {
    headline: "Các quy tắc nghiệp vụ được mã hóa trong sản phẩm.",
    items: [
      "Lesson là đơn vị nguyên tử.",
      "Quản lý ghi; giáo viên đọc.",
      "Thù lao được suy ra từ số giờ đã dạy.",
      "Buổi hủy và no-show không được trả.",
      "VND được suy ra từ một tỷ giá USD.",
      "Chiều cao buổi học phản ánh thời lượng.",
      "Rủi ro xếp lịch được suy ra, không nhập tay.",
    ],
  },
  architecture: {
    headline: "Được xây dựng như một hệ thống sản phẩm, không phải mockup portfolio tĩnh.",
    body: [
      "Next.js App Router, React và TypeScript với mô hình miền Lesson có kiểu.",
      "Màn quản lý và giáo viên chiếu cùng một store trong bộ nhớ qua hook dùng chung.",
      "Xung đột, khoảng di chuyển và thù lao được suy ra bằng hàm miền thuần — không nhập tay.",
      "UI gọi qua lớp DataSource, nên API thật có thể thay fixture mà không viết lại màn hình.",
      "Primitive tái sử dụng (Badge, MoneyPair, thẻ lịch) giữ hai vai trò nhất quán về hình ảnh.",
    ],
    honesty:
      "Bản công khai hiện tại là nguyên mẫu front-end độ trung thực cao. Xác thực, lưu trữ và API sản xuất nằm ngoài phạm vi demo này.",
  },
  footer: {
    headline: "Xem tư duy sản phẩm đang hoạt động.",
    credit: "Thiết kế và xây dựng bởi Daniel Aleksandrov",
    role: "Frontend Developer · React · Next.js · TypeScript",
    managerLink: "Demo quản lý",
    teacherLink: "Góc giáo viên",
  },
  positioning:
    "Xây quanh vận hành trường ngoại ngữ thực tế. Thiết kế cho xếp lịch giáo dục phức tạp.",
};
